name: E2E Tests

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      access_token:
        required: true
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: aramos20/github-actions-course-example-e2e
          ref: main
          secrets: ${{ secrets.access_token || secrets.GITHUB_TOKEN }}

      - name: Setup code
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests
        run: npm run test:e2e
